name: Setup cross-compiler (build on the fly)
description: >
  Builds a static gfortran/gcc cross-toolchain for macOS inside the caller’s job.
inputs:
  gcc:
    description: GCC version (major.minor.patch)
    default: "14.2.0"
  target_arch:
    description: Target architecture (arm64 | x86_64)
    required: true
runs:
  using: composite
  steps:
    # 1. checkout THIS repository (the action’s source)
    - uses: actions/checkout@v4
      with: { path: cross-src }

    # 2. install micromamba + deps (same recipe you already have)
    - uses: mamba-org/setup-micromamba@v1
      with:
        init-shell: bash          
        cache-downloads: true     
        cache-env: true           

    # 3. build the toolchain
    - name: Build static cross-compiler
      shell: bash
      run: |
        BUILD_ARCH=$(uname -m)                # arm64 or x86_64
        bash cross-src/scripts/build_gfortran.sh \
             "${{ inputs.gcc }}" \
             "${{ inputs.target_arch }}" \
             "$BUILD_ARCH"

    # 4. expose wrappers and env vars to later steps
    - name: Expose FC / CC / CXX
      shell: bash
      run: |
        TOOLROOT="$CONDA_PREFIX"            # where the compiler actually lives
        WRAPPER_DIR="$PWD/cross-src/bin"    # <-- lives in the checkout

        mkdir -p "$WRAPPER_DIR"
        ln -sf "$TOOLROOT/bin/gfortran" "$WRAPPER_DIR/cross-gfortran"
        ln -sf "$TOOLROOT/bin/gcc"      "$WRAPPER_DIR/cross-gcc"
        ln -sf "$TOOLROOT/bin/g++"      "$WRAPPER_DIR/cross-g++"

        echo "$WRAPPER_DIR" >> "$GITHUB_PATH"
        {
          echo "FC=cross-gfortran"
          echo "CC=cross-gcc"
          echo "CXX=cross-g++"
        } >> "$GITHUB_ENV"
