name: build-gfortran-darwin

on:
  workflow_dispatch:
  push:
    tags: [ 'gcc-*' ]

jobs:
  build:
    # ── 1. two host machines ────────────────────────────────────────────────
    strategy:
      matrix:
        include:
          # Intel host
          - runner: macos-13             # GitHub macOS Intel runner
            build_arch: x86_64
          # Apple-Silicon host
          - runner: macos-14             # GitHub macOS ARM runner
            build_arch: arm64
        gcc: [14.2.0]                    # bump here for a new release

    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v4

    - name: Install micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        init-shell: bash
        cache-downloads: true
        cache-env: true

    # ── 2. build for arm64 targets (native on apple-silicon, cross on intel) ─
    - name: Build compiler for arm64 targets
      run: |
        bash scripts/build_gfortran.sh \
          "${{ matrix.gcc }}" \
          arm64 \
          "${{ matrix.build_arch }}"

    # ── 3. build for x86_64 targets (native on intel, cross on apple-silicon) ─
    - name: Build compiler for x86_64 targets
      run: |
        bash scripts/build_gfortran.sh \
          "${{ matrix.gcc }}" \
          x86_64 \
          "${{ matrix.build_arch }}"

    # ── 4. upload whatever tarballs were produced in this job ────────────────
    - name: Upload artefacts
      uses: actions/upload-artifact@v4
      with:
        name: gfortran-${{ matrix.build_arch }}-${{ matrix.gcc }}
        path: gfortran-darwin-*.tar.gz
