name: build-gfortran-darwin

on:
  workflow_dispatch:            # manual run button
  push:
    tags: [ 'gcc-*' ]           # e.g.  gcc-14.3.0

jobs:
  build:
    strategy:
      matrix:
        arch: [x86_64, arm64]
        gcc:  [14.2.0]          # bump here for a new release
    runs-on: macos-14           # Intel runner; can cross-build arm64

    steps:
    - uses: actions/checkout@v4

    - name: Install micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        init-shell: bash
        cache-downloads: true
        cache-env: true

    - name: Build compiler
      run: |
        case "${{ runner.arch }}" in
          X64)   BUILD_ARCH="x86_64" ;;
          ARM64) BUILD_ARCH="arm64"  ;;
          *)     echo "Unknown runner.arch"; exit 1 ;;
        esac

        bash scripts/build_gfortran.sh \
          "${{ matrix.gcc }}"   \  # ver
          "${{ matrix.arch }}"  \  # target arch
          "${BUILD_ARCH}"          # build arch (detected)      
      
    - name: Upload artefact
      uses: actions/upload-artifact@v4
      with:
        name: gfortran-${{ matrix.arch }}-${{ matrix.gcc }}
        path: gfortran-darwin-${{ matrix.arch }}-*.tar.gz

