name: build-gfortran-darwin

on:
  workflow_dispatch:
  push:
    tags: [ 'gcc-*' ]

# 1. four-way matrix: host (build_arch) x target_arch
#    Intel runner for x86_64 host, Apple-silicon runner for arm64 host
jobs:
  build:
    strategy:
      matrix:
        build_arch:  [x86_64, arm64]        # host CPU
        target_arch: [x86_64, arm64]        # toolchain target
        gcc:         [14.2.0]
    runs-on: ${{ matrix.build_arch == 'arm64' && 'macos-14' || 'macos-13' }}    

    steps:
    - uses: actions/checkout@v4

    - name: Install micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        init-shell: bash
        cache-downloads: true
        cache-env: true

    # (2) single call – the matrix already supplies both arches
    - name: Build compiler
      run: >
        bash scripts/build_gfortran.sh
        "${{ matrix.gcc }}"
        "${{ matrix.target_arch }}"
        "${{ matrix.build_arch }}"        
        
    # (3) upload whatever tarballs were produced in this job ────────────────
    - name: Upload artefacts
      uses: actions/upload-artifact@v4
      with:
        name: gfortran-${{ matrix.target_arch }}-${{ matrix.build_arch }}-${{ matrix.gcc }}
        path: gfortran-darwin-${{ matrix.target_arch }}-*.tar.gz        
